name: Paper_with_Code_bot

on:
  schedule:
    # UTC 00:00
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      # pip及びpytestのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job
        run:
          python main.py
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
